# Результаты тестов HSV красного, желтого и зеленого цвета:

<pre>
<span style="font-size: 20px;">
1.Красный фонарь:
  [ 10 170   4 175 172 168  21  25  27  15]
  [176   2   4  11 169   8 167  17 163 132]
  [ 12   4  10 167  29  26  24  20  17]
  [176   6   4 170  26  20  22 164  17  13]

2.Зелёный уличный фонарь:
  [ 80  90  83  87 101  96 103 120 114 110]
  [80 67 69 65 56 52 43 38 98 92]
  [ 90  80  78  85  74  69  71 170 103  95]
  [79 76 72 83 66 70 43 35 55 51]

3.Жёлтый уличный фонарь:
  [30 13 24 17 26 20 15  7  4 22]
  [ 30   9   2  22   5 174  15 178 170  17]
  [30 18 23 13  7  4]
  [ 30 174 170   5 177 167 159 164  10   8]
</span>
</pre>


<span style="font-size: 20px;">Импорт в библиотеку, чтение изображений и преобразование в HSV изображения.</span> 


In [103]:
import cv2 as cv
import numpy as np
import os

my_path = "D:/Projects/Pycharm_projects/CV/lab01/tlights"
my_img = []

# Просмотр изображений в папке
for i in os.listdir(my_path):
    if i.endswith(".jpg"):
        img_path = os.path.join(my_path, i)
        my_img.append(img_path)

# Конвертация изображений
images_bgr = []
images_rgb = []
images_hsv = []

for img_path in my_img:
    img_bgr = cv.imread(img_path)
    img_rgb = cv.cvtColor(img_bgr, cv.COLOR_BGR2RGB)
    img_hsv = cv.cvtColor(img_rgb, cv.COLOR_RGB2HSV)
    
    images_bgr.append(img_bgr)
    images_rgb.append(img_rgb)
    images_hsv.append(img_hsv)


In [104]:
# Сохранить результаты классификации
red_images = []
green_images = []
yellow_images = []
unknown_images = []

# Обработка и классификация
for i, img_hsv in enumerate(images_hsv):
    # Создать маску
    # Красная маска
    low_red = np.array([0, 80,20])
    up_red = np.array([12, 200, 220])
    red_mask_low = (img_hsv[:,:,0] >= low_red[0]) & \
                   (img_hsv[:,:,0] <= up_red[0]) & \
                   (img_hsv[:,:,1] >= low_red[1]) & \
                   (img_hsv[:,:,1] <= up_red[1]) & \
                   (img_hsv[:,:,2] >= low_red[2]) & \
                   (img_hsv[:,:,2] <= up_red[2])

    low_red = np.array([163, 80, 20])
    up_red = np.array([179, 255, 255])
    red_mask_high = (img_hsv[:,:,0] >= low_red[0]) & \
                    (img_hsv[:,:,0] <= up_red[0]) & \
                    (img_hsv[:,:,1] >= low_red[1]) & \
                    (img_hsv[:,:,1] <= up_red[1]) & \
                    (img_hsv[:,:,2] >= low_red[2]) & \
                    (img_hsv[:,:,2] <= up_red[2])

    red_mask = red_mask_low | red_mask_high
    red_pixels = np.sum(red_mask)

    # Зеленая маска
    low_green = np.array([43, 100,120])
    up_green = np.array([90, 255, 255])
    green_mask = (img_hsv[:,:,0] >= low_green[0]) & \
                 (img_hsv[:,:,0] <= up_green[0]) & \
                 (img_hsv[:,:,1] >= low_green[1]) & \
                 (img_hsv[:,:,1] <= up_green[1]) & \
                 (img_hsv[:,:,2] >= low_green[2]) & \
                 (img_hsv[:,:,2] <= up_green[2])
    green_pixels = np.sum(green_mask)
    
    # Жёлтая маска
    low_yellow = np.array([18,80, 110])
    up_yellow = np.array([33, 230, 255])
    yellow_mask = (img_hsv[:,:,0] >= low_yellow[0]) & \
                  (img_hsv[:,:,0] <= up_yellow[0]) & \
                  (img_hsv[:,:,1] >= low_yellow[1]) & \
                  (img_hsv[:,:,1] <= up_yellow[1]) & \
                  (img_hsv[:,:,2] >= low_yellow[2]) & \
                  (img_hsv[:,:,2] <= up_yellow[2])
    yellow_pixels = np.sum(yellow_mask)

    # Классификация: количество пикселей в каком цвете больше, чем в каком цветовом файле
    if red_pixels > green_pixels and red_pixels > yellow_pixels:
        red_images.append(my_img[i])
    elif green_pixels > red_pixels and green_pixels > yellow_pixels:
        green_images.append(my_img[i])
    elif yellow_pixels > red_pixels and yellow_pixels > green_pixels:
        yellow_images.append(my_img[i])
    else:
        unknown_images.append(my_img[i])



In [105]:
# Сохранить результаты
with open("red.txt", "w") as red_file:
    for red_img in red_images:
        red_file.write(red_img + "\n")

with open("green.txt", "w") as green_file:
    for green_img in green_images:
        green_file.write(green_img + "\n")

with open("yellow.txt", "w") as yellow_file:
    for yellow_img in yellow_images:
        yellow_file.write(yellow_img + "\n")

print('Everything is ok!')

Everything is ok!
